#!/usr/bin/env bash
# Patch 86 voor hrmforce-site: de controle op patch 85. Vijf vondsten, geen
# DeepL nodig, alle vertalingen zitten in de patch.
#
#   bash toepassen-86.sh
#
# 1. DeepL las "Lets" (de taal) als het Engelse "let's" en maakte er in alle
#    drie de talen een werkwoord van: "Pozwolmy", "Lad os", "Lat oss". "Ests"
#    bleef onvertaald staan. Alle 29 taalnamen staan nu met de hand goed in
#    het Pools, Deens en Zweeds.
# 2. Het label "Taal kandidaat" bleef in elke taal Nederlands. De sleutel heet
#    "lang" en die staat in GEEN_TEKST van de vertaallaag, waar hij als
#    taalcode geldt en niet als tekst. De sleutel heet nu "taalLabel".
# 3. De Poolse aanhef werd "Szanowny Panie", dus mannelijk. Nu "Dzien dobry".
#    Het Zweedse "Kara" is te familiair voor een zakelijke mail en werd "Hej",
#    en het Deense "Kaere," zonder naam werd "Hej,".
# 4. Het Poolse onderwerp van de antwoordmail werd "Prosimy kierowac na adres
#    hrmforce", dus een opdracht in plaats van een onderwerp. Nu "Twoje
#    zgloszenie w hrmforce". Verder een paar losse correcties: het Zweedse
#    "den riktiga frageformularet" moet "det" zijn, het Deense "Engangs kob"
#    is een woord, en de Poolse productomschrijving begon met "{name} Jest to".
# 5. De productomschrijving in de shop stond in negen talen in de bron van elke
#    shoppagina. Nu alleen de eigen taal, dus geen Nederlands meer onder een
#    Poolse url en ruim 4 kB minder per pagina.
set -euo pipefail
cd "$(dirname "$0")"
[ -d src/i18n ] || { echo "Draai dit vanuit de hoofdmap van hrmforce-site."; exit 1; }

cat > /tmp/86.b64 <<'B64EOF'
ZGlmZiAtLWdpdCBhL2Z1bmN0aW9ucy9fbGliL21haWx0ZWtzdGVuLmpzIGIvZnVuY3Rpb25zL19s
aWIvbWFpbHRla3N0ZW4uanMKaW5kZXggMWExOWE5Ny4uZmIxMjUwYiAxMDA2NDQKLS0tIGEvZnVu
Y3Rpb25zL19saWIvbWFpbHRla3N0ZW4uanMKKysrIGIvZnVuY3Rpb25zL19saWIvbWFpbHRla3N0
ZW4uanMKQEAgLTkgKzkgQEAgZXhwb3J0IGNvbnN0IFBBUlRJQ1VMSUVSX0VYVFJBID0gewotICAg
ICJhYW5oZWYiOiAiS8OmcmUsIiwKKyAgICAiYWFuaGVmIjogIkhlaiwiLApAQCAtMTgsMyArMTgs
MyBAQCBleHBvcnQgY29uc3QgUEFSVElDVUxJRVJfRVhUUkEgPSB7Ci0gICAgIm9uZGVyd2VycCI6
ICJQYcWEc3R3YSB6YXB5dGFuaWUgcHJvc2lteSBraWVyb3dhxIcgbmEgYWRyZXMgaHJtZm9yY2Ui
LAotICAgICJhYW5oZWZOYWFtIjogIlN6YW5vd255IFBhbmllIHtuYWFtfSwiLAotICAgICJhYW5o
ZWYiOiAiU3phbm93bmkgUGHFhHN0d28sIiwKKyAgICAib25kZXJ3ZXJwIjogIlR3b2plIHpnxYJv
c3plbmllIHcgaHJtZm9yY2UiLAorICAgICJhYW5oZWZOYWFtIjogIkR6aWXFhCBkb2JyeSB7bmFh
bX0sIiwKKyAgICAiYWFuaGVmIjogIkR6aWXFhCBkb2JyeSwiLApAQCAtMzAsMiArMzAsMiBAQCBl
eHBvcnQgY29uc3QgUEFSVElDVUxJRVJfRVhUUkEgPSB7Ci0gICAgImFhbmhlZk5hYW0iOiAiS8Ok
cmEge25hYW19LCIsCi0gICAgImFhbmhlZiI6ICJCw6RzdGUsIiwKKyAgICAiYWFuaGVmTmFhbSI6
ICJIZWoge25hYW19LCIsCisgICAgImFhbmhlZiI6ICJIZWosIiwKQEAgLTU1LDMgKzU1LDMgQEAg
ZXhwb3J0IGNvbnN0IE9FRkVOX0VYVFJBID0gewotICAgICJvbmRlcndlcnBWb29yIjogIlB5dGFu
aWEgxId3aWN6ZW5pb3dlIGRvdHljesSFY2Ugc3Ryb255IHt0aXRlbH0iLAotICAgICJoYWxsb05h
YW0iOiAiV2l0YW0sIHtuYWFtfSwiLAotICAgICJoYWxsbyI6ICJXaXRhbSwiLAorICAgICJvbmRl
cndlcnBWb29yIjogIlB5dGFuaWEgxId3aWN6ZW5pb3dlOiB7dGl0ZWx9IiwKKyAgICAiaGFsbG9O
YWFtIjogIkR6aWXFhCBkb2JyeSB7bmFhbX0sIiwKKyAgICAiaGFsbG8iOiAiRHppZcWEIGRvYnJ5
LCIsCkBAIC03MiArNzIgQEAgZXhwb3J0IGNvbnN0IE9FRkVOX0VYVFJBID0gewotICAgICJsZXQi
OiAiRG9rdW1lbnRldCBpbm5laMOlbGxlciBleGVtcGVsZnLDpWdvci4gRGUga29tbWVyIGludGUg
ZnLDpW4gZGVuIHJpa3RpZ2EgZnLDpWdlZm9ybXVsw6RyZXQgb2NoIGRpbmEgc3ZhciBzcGFyYXMg
aW50ZS4iLAorICAgICJsZXQiOiAiRG9rdW1lbnRldCBpbm5laMOlbGxlciBleGVtcGVsZnLDpWdv
ci4gRGUga29tbWVyIGludGUgZnLDpW4gZGV0IHJpa3RpZ2EgZnLDpWdlZm9ybXVsw6RyZXQgb2No
IGRpbmEgc3ZhciBzcGFyYXMgaW50ZS4iLApkaWZmIC0tZ2l0IGEvc3JjL2NvbXBvbmVudHMvU2hv
cC5hc3RybyBiL3NyYy9jb21wb25lbnRzL1Nob3AuYXN0cm8KaW5kZXggYjAwMTMyYy4uODUwYjYx
OCAxMDA2NDQKLS0tIGEvc3JjL2NvbXBvbmVudHMvU2hvcC5hc3RybworKysgYi9zcmMvY29tcG9u
ZW50cy9TaG9wLmFzdHJvCkBAIC0zMiArMzIsMyBAQCBjb25zdCBFTlJJQ0ggPSB7Ci0gIGRlc2M6
IFNIT1BfRU5SSUNIX0RFU0MsCisgIC8vIEFsbGVlbiBkZSBlaWdlbiB0YWFsOiBhbmRlcnMgc3Rh
YXQgZGUgb21zY2hyaWp2aW5nIGluIG5lZ2VuIHRhbGVuIGluIGRlCisgIC8vIGJyb24gdmFuIGVs
a2Ugc2hvcHBhZ2luYSwgZHVzIG9vayBOZWRlcmxhbmRzIG9uZGVyIGVlbiBQb29sc2UgdXJsLgor
ICBkZXNjOiBTSE9QX0VOUklDSF9ERVNDW2xhbmddIHx8IFNIT1BfRU5SSUNIX0RFU0MubmwsCkBA
IC0zNjYgKzM2OCBAQCBjb25zdCBNQ19CRVpJRyA9IFNIT1BfTUNfQkVaSUc7Ci0gICAgZnVuY3Rp
b24gZW5yaWNoRChwKSB7IHJldHVybiBFTlJJQ0guZGVzY1tMQU5HXSB8fCBFTlJJQ0guZGVzYy5u
bDsgfQorICAgIGZ1bmN0aW9uIGVucmljaEQocCkgeyByZXR1cm4gRU5SSUNILmRlc2M7IH0KQEAg
LTQ1MiArNDU0IEBAIGNvbnN0IE1DX0JFWklHID0gU0hPUF9NQ19CRVpJRzsKLSAgICAgIHJldHVy
biAnPGRpdiBjbGFzcz0iY2FuZCIgZGF0YS1saW5lPSInICsgbC5saW5lSWQgKyAnIiBkYXRhLWlk
eD0iJyArIGkgKyAnIj4nICsgKGwucXR5ID4gMSA/ICc8ZGl2IGNsYXNzPSJjYW5kLWgiPicgKyBl
c2MoQy5oZWFkaW5nKSArICIgIiArIG4gKyAiPC9kaXY+IiA6ICIiKSArICc8aW5wdXQgY2xhc3M9
ImNhbmQtbmFtZSIgdHlwZT0idGV4dCIgcGxhY2Vob2xkZXI9IicgKyBlc2MoQy5uYW1lKSArICci
IHZhbHVlPSInICsgZXNjKHZOKSArICciPjxpbnB1dCBjbGFzcz0iY2FuZC1tYWlsIiB0eXBlPSJl
bWFpbCIgcGxhY2Vob2xkZXI9IicgKyBlc2MoQy5lbWFpbCkgKyAnIiB2YWx1ZT0iJyArIGVzYyh2
RSkgKyAnIj48ZGl2IGNsYXNzPSJjYW5kLXJvdyI+PHNlbGVjdCBjbGFzcz0iY2FuZC1sYW5nIiBh
cmlhLWxhYmVsPSInICsgZXNjKEMubGFuZykgKyAnIj4nICsgbG8gKyAnPC9zZWxlY3Q+PHNlbGVj
dCBjbGFzcz0iY2FuZC1sZXZlbCIgYXJpYS1sYWJlbD0iJyArIGVzYyhDLmxldmVsKSArICciPicg
KyB2byArICI8L3NlbGVjdD48L2Rpdj48L2Rpdj4iOworICAgICAgcmV0dXJuICc8ZGl2IGNsYXNz
PSJjYW5kIiBkYXRhLWxpbmU9IicgKyBsLmxpbmVJZCArICciIGRhdGEtaWR4PSInICsgaSArICci
PicgKyAobC5xdHkgPiAxID8gJzxkaXYgY2xhc3M9ImNhbmQtaCI+JyArIGVzYyhDLmhlYWRpbmcp
ICsgIiAiICsgbiArICI8L2Rpdj4iIDogIiIpICsgJzxpbnB1dCBjbGFzcz0iY2FuZC1uYW1lIiB0
eXBlPSJ0ZXh0IiBwbGFjZWhvbGRlcj0iJyArIGVzYyhDLm5hbWUpICsgJyIgdmFsdWU9IicgKyBl
c2Modk4pICsgJyI+PGlucHV0IGNsYXNzPSJjYW5kLW1haWwiIHR5cGU9ImVtYWlsIiBwbGFjZWhv
bGRlcj0iJyArIGVzYyhDLmVtYWlsKSArICciIHZhbHVlPSInICsgZXNjKHZFKSArICciPjxkaXYg
Y2xhc3M9ImNhbmQtcm93Ij48c2VsZWN0IGNsYXNzPSJjYW5kLWxhbmciIGFyaWEtbGFiZWw9Iicg
KyBlc2MoQy50YWFsTGFiZWwpICsgJyI+JyArIGxvICsgJzwvc2VsZWN0PjxzZWxlY3QgY2xhc3M9
ImNhbmQtbGV2ZWwiIGFyaWEtbGFiZWw9IicgKyBlc2MoQy5sZXZlbCkgKyAnIj4nICsgdm8gKyAi
PC9zZWxlY3Q+PC9kaXY+PC9kaXY+IjsKZGlmZiAtLWdpdCBhL3NyYy9kYXRhL2NvbXBvbmVudC10
ZWtzdGVuLmpzIGIvc3JjL2RhdGEvY29tcG9uZW50LXRla3N0ZW4uanMKaW5kZXggNWMyMmUwZi4u
MDYzMDY4OCAxMDA2NDQKLS0tIGEvc3JjL2RhdGEvY29tcG9uZW50LXRla3N0ZW4uanMKKysrIGIv
c3JjL2RhdGEvY29tcG9uZW50LXRla3N0ZW4uanMKQEAgLTI1LDAgKzI2LDIgQEAgZXhwb3J0IGNv
bnN0IFNIT1BfUkVRX0kxOE4gPSB7CisvLyB0YWFsTGFiZWwsIG5pZXQgbGFuZzogJ2xhbmcnIHN0
YWF0IGluIEdFRU5fVEVLU1QgdmFuIGRlIHZlcnRhYWxsYWFnIChkYWFyIGlzCisvLyBoZXQgZWVu
IHRhYWxjb2RlLCBnZWVuIHRla3N0KSwgd2FhcmRvb3IgZGl0IGxhYmVsIGluIGVsa2UgdGFhbCBO
ZWRlcmxhbmRzIGJsZWVmLgpAQCAtMjcsNiArMjksNiBAQCBleHBvcnQgY29uc3QgU0hPUF9DQU5E
X0kxOE4gPSB7Ci0gIG5sOiB7IGhlYWRpbmc6ICJLYW5kaWRhYXQiLCBuYW1lOiAiTmFhbSBrYW5k
aWRhYXQiLCBlbWFpbDogIkUtbWFpbCBrYW5kaWRhYXQiLCBsYW5nOiAiVGFhbCBrYW5kaWRhYXQi
LCBsZXZlbDogIk5pdmVhdSIsIHBpY2s6ICJLaWVz4oCmIiwgbGFuZ3M6IFtbIm5sIiwiTmVkZXJs
YW5kcyJdLFsibmwtQkUiLCJOZWRlcmxhbmRzIChCZWxnacOrKSJdLFsiZW4iLCJFbmdlbHMgKFZL
KSJdLFsiZW4tVVMiLCJFbmdlbHMgKFZTKSJdLFsiZGUiLCJEdWl0cyJdLFsiZnIiLCJGcmFucyJd
LFsiZXMiLCJTcGFhbnMiXSxbIml0IiwiSXRhbGlhYW5zIl0sWyJwdCIsIlBvcnR1Z2VlcyJdLFsi
cGwiLCJQb29scyJdLFsiY3MiLCJUc2plY2hpc2NoIl0sWyJzayIsIlNsb3dhYWtzIl0sWyJodSIs
IkhvbmdhYXJzIl0sWyJybyIsIlJvZW1lZW5zIl0sWyJydSIsIlJ1c3Npc2NoIl0sWyJ1ayIsIk9l
a3Jhw69lbnMiXSxbImJnIiwiQnVsZ2FhcnMiXSxbImhyIiwiS3JvYXRpc2NoIl0sWyJzciIsIlNl
cnZpc2NoIl0sWyJzbCIsIlNsb3ZlZW5zIl0sWyJlbCIsIkdyaWVrcyJdLFsidHIiLCJUdXJrcyJd
LFsic3YiLCJad2VlZHMiXSxbImRhIiwiRGVlbnMiXSxbIm5iIiwiTm9vcnMiXSxbImZpIiwiRmlu
cyJdLFsibHQiLCJMaXRvdXdzIl0sWyJsdiIsIkxldHMiXSxbImV0IiwiRXN0cyJdXSwgbGV2ZWxz
OiBbWyJvcGVyYXRpb25hbCIsIk9wZXJhdGlvbmFsIl0sWyJiYWNoZWxvciIsIkJhY2hlbG9yIl0s
WyJtYXN0ZXIiLCJNYXN0ZXIiXV0gfSwKLSAgZW46IHsgaGVhZGluZzogIkNhbmRpZGF0ZSIsIG5h
bWU6ICJDYW5kaWRhdGUgbmFtZSIsIGVtYWlsOiAiQ2FuZGlkYXRlIGVtYWlsIiwgbGFuZzogIkNh
bmRpZGF0ZSBsYW5ndWFnZSIsIGxldmVsOiAiTGV2ZWwiLCBwaWNrOiAiQ2hvb3Nl4oCmIiwgbGFu
Z3M6IFtbIm5sIiwiRHV0Y2giXSxbIm5sLUJFIiwiRHV0Y2ggKEJlbGdpdW0pIl0sWyJlbiIsIkVu
Z2xpc2ggKFVLKSJdLFsiZW4tVVMiLCJFbmdsaXNoIChVUykiXSxbImRlIiwiR2VybWFuIl0sWyJm
ciIsIkZyZW5jaCJdLFsiZXMiLCJTcGFuaXNoIl0sWyJpdCIsIkl0YWxpYW4iXSxbInB0IiwiUG9y
dHVndWVzZSJdLFsicGwiLCJQb2xpc2giXSxbImNzIiwiQ3plY2giXSxbInNrIiwiU2xvdmFrIl0s
WyJodSIsIkh1bmdhcmlhbiJdLFsicm8iLCJSb21hbmlhbiJdLFsicnUiLCJSdXNzaWFuIl0sWyJ1
ayIsIlVrcmFpbmlhbiJdLFsiYmciLCJCdWxnYXJpYW4iXSxbImhyIiwiQ3JvYXRpYW4iXSxbInNy
IiwiU2VyYmlhbiJdLFsic2wiLCJTbG92ZW5pYW4iXSxbImVsIiwiR3JlZWsiXSxbInRyIiwiVHVy
a2lzaCJdLFsic3YiLCJTd2VkaXNoIl0sWyJkYSIsIkRhbmlzaCJdLFsibmIiLCJOb3J3ZWdpYW4i
XSxbImZpIiwiRmlubmlzaCJdLFsibHQiLCJMaXRodWFuaWFuIl0sWyJsdiIsIkxhdHZpYW4iXSxb
ImV0IiwiRXN0b25pYW4iXV0sIGxldmVsczogW1sib3BlcmF0aW9uYWwiLCJPcGVyYXRpb25hbCJd
LFsiYmFjaGVsb3IiLCJCYWNoZWxvciJdLFsibWFzdGVyIiwiTWFzdGVyIl1dIH0sCi0gIGRlOiB7
IGhlYWRpbmc6ICJLYW5kaWRhdCIsIG5hbWU6ICJOYW1lIGRlcyBLYW5kaWRhdGVuIiwgZW1haWw6
ICJFLU1haWwgZGVzIEthbmRpZGF0ZW4iLCBsYW5nOiAiU3ByYWNoZSIsIGxldmVsOiAiTml2ZWF1
IiwgcGljazogIlfDpGhsZW7igKYiLCBsYW5nczogW1sibmwiLCJOaWVkZXJsw6RuZGlzY2giXSxb
Im5sLUJFIiwiTmllZGVybMOkbmRpc2NoIChCZWxnaWVuKSJdLFsiZW4iLCJFbmdsaXNjaCAoVUsp
Il0sWyJlbi1VUyIsIkVuZ2xpc2NoIChVU0EpIl0sWyJkZSIsIkRldXRzY2giXSxbImZyIiwiRnJh
bnrDtnNpc2NoIl0sWyJlcyIsIlNwYW5pc2NoIl0sWyJpdCIsIkl0YWxpZW5pc2NoIl0sWyJwdCIs
IlBvcnR1Z2llc2lzY2giXSxbInBsIiwiUG9sbmlzY2giXSxbImNzIiwiVHNjaGVjaGlzY2giXSxb
InNrIiwiU2xvd2FraXNjaCJdLFsiaHUiLCJVbmdhcmlzY2giXSxbInJvIiwiUnVtw6RuaXNjaCJd
LFsicnUiLCJSdXNzaXNjaCJdLFsidWsiLCJVa3JhaW5pc2NoIl0sWyJiZyIsIkJ1bGdhcmlzY2gi
XSxbImhyIiwiS3JvYXRpc2NoIl0sWyJzciIsIlNlcmJpc2NoIl0sWyJzbCIsIlNsb3dlbmlzY2gi
XSxbImVsIiwiR3JpZWNoaXNjaCJdLFsidHIiLCJUw7xya2lzY2giXSxbInN2IiwiU2Nod2VkaXNj
aCJdLFsiZGEiLCJEw6RuaXNjaCJdLFsibmIiLCJOb3J3ZWdpc2NoIl0sWyJmaSIsIkZpbm5pc2No
Il0sWyJsdCIsIkxpdGF1aXNjaCJdLFsibHYiLCJMZXR0aXNjaCJdLFsiZXQiLCJFc3RuaXNjaCJd
XSwgbGV2ZWxzOiBbWyJvcGVyYXRpb25hbCIsIk9wZXJhdGlvbmFsIl0sWyJiYWNoZWxvciIsIkJh
Y2hlbG9yIl0sWyJtYXN0ZXIiLCJNYXN0ZXIiXV0gfSwKLSAgZnI6IHsgaGVhZGluZzogIkNhbmRp
ZGF0IiwgbmFtZTogIk5vbSBkdSBjYW5kaWRhdCIsIGVtYWlsOiAiRS1tYWlsIGR1IGNhbmRpZGF0
IiwgbGFuZzogIkxhbmd1ZSIsIGxldmVsOiAiTml2ZWF1IiwgcGljazogIkNob2lzaXLigKYiLCBs
YW5nczogW1sibmwiLCJOw6llcmxhbmRhaXMiXSxbIm5sLUJFIiwiTsOpZXJsYW5kYWlzIChCZWxn
aXF1ZSkiXSxbImVuIiwiQW5nbGFpcyAoUlUpIl0sWyJlbi1VUyIsIkFuZ2xhaXMgKFVTKSJdLFsi
ZGUiLCJBbGxlbWFuZCJdLFsiZnIiLCJGcmFuw6dhaXMiXSxbImVzIiwiRXNwYWdub2wiXSxbIml0
IiwiSXRhbGllbiJdLFsicHQiLCJQb3J0dWdhaXMiXSxbInBsIiwiUG9sb25haXMiXSxbImNzIiwi
VGNow6hxdWUiXSxbInNrIiwiU2xvdmFxdWUiXSxbImh1IiwiSG9uZ3JvaXMiXSxbInJvIiwiUm91
bWFpbiJdLFsicnUiLCJSdXNzZSJdLFsidWsiLCJVa3JhaW5pZW4iXSxbImJnIiwiQnVsZ2FyZSJd
LFsiaHIiLCJDcm9hdGUiXSxbInNyIiwiU2VyYmUiXSxbInNsIiwiU2xvdsOobmUiXSxbImVsIiwi
R3JlYyJdLFsidHIiLCJUdXJjIl0sWyJzdiIsIlN1w6lkb2lzIl0sWyJkYSIsIkRhbm9pcyJdLFsi
bmIiLCJOb3J2w6lnaWVuIl0sWyJmaSIsIkZpbm5vaXMiXSxbImx0IiwiTGl0dWFuaWVuIl0sWyJs
diIsIkxldHRvbiJdLFsiZXQiLCJFc3RvbmllbiJdXSwgbGV2ZWxzOiBbWyJvcGVyYXRpb25hbCIs
Ik9ww6lyYXRpb25uZWwiXSxbImJhY2hlbG9yIiwiQmFjaGVsb3IiXSxbIm1hc3RlciIsIk1hc3Rl
ciJdXSB9LAotICBlczogeyBoZWFkaW5nOiAiQ2FuZGlkYXRvIiwgbmFtZTogIk5vbWJyZSBkZWwg
Y2FuZGlkYXRvIiwgZW1haWw6ICJDb3JyZW8gZGVsIGNhbmRpZGF0byIsIGxhbmc6ICJJZGlvbWEi
LCBsZXZlbDogIk5pdmVsIiwgcGljazogIkVsZWdpcuKApiIsIGxhbmdzOiBbWyJubCIsIk5lZXJs
YW5kw6lzIl0sWyJubC1CRSIsIk5lZXJsYW5kw6lzIChCw6lsZ2ljYSkiXSxbImVuIiwiSW5nbMOp
cyAoUlUpIl0sWyJlbi1VUyIsIkluZ2zDqXMgKEVFLiBVVS4pIl0sWyJkZSIsIkFsZW3DoW4iXSxb
ImZyIiwiRnJhbmPDqXMiXSxbImVzIiwiRXNwYcOxb2wiXSxbIml0IiwiSXRhbGlhbm8iXSxbInB0
IiwiUG9ydHVndcOpcyJdLFsicGwiLCJQb2xhY28iXSxbImNzIiwiQ2hlY28iXSxbInNrIiwiRXNs
b3ZhY28iXSxbImh1IiwiSMO6bmdhcm8iXSxbInJvIiwiUnVtYW5vIl0sWyJydSIsIlJ1c28iXSxb
InVrIiwiVWNyYW5pYW5vIl0sWyJiZyIsIkLDumxnYXJvIl0sWyJociIsIkNyb2F0YSJdLFsic3Ii
LCJTZXJiaW8iXSxbInNsIiwiRXNsb3Zlbm8iXSxbImVsIiwiR3JpZWdvIl0sWyJ0ciIsIlR1cmNv
Il0sWyJzdiIsIlN1ZWNvIl0sWyJkYSIsIkRhbsOpcyJdLFsibmIiLCJOb3J1ZWdvIl0sWyJmaSIs
IkZpbsOpcyJdLFsibHQiLCJMaXR1YW5vIl0sWyJsdiIsIkxldMOzbiJdLFsiZXQiLCJFc3Rvbmlv
Il1dLCBsZXZlbHM6IFtbIm9wZXJhdGlvbmFsIiwiT3BlcmFjaW9uYWwiXSxbImJhY2hlbG9yIiwi
QmFjaGVsb3IiXSxbIm1hc3RlciIsIk3DoXN0ZXIiXV0gfSwKLSAgcm86IHsgaGVhZGluZzogIkNh
bmRpZGF0IiwgbmFtZTogIk51bWVsZSBjYW5kaWRhdHVsdWkiLCBlbWFpbDogIkUtbWFpbHVsIGNh
bmRpZGF0dWx1aSIsIGxhbmc6ICJMaW1ixIMiLCBsZXZlbDogIk5pdmVsIiwgcGljazogIkFsZWdl
4oCmIiwgbGFuZ3M6IFtbIm5sIiwiTmVlcmxhbmRlesSDIl0sWyJubC1CRSIsIk5lZXJsYW5kZXrE
gyAoQmVsZ2lhKSJdLFsiZW4iLCJFbmdsZXrEgyAoVUspIl0sWyJlbi1VUyIsIkVuZ2xlesSDIChT
VUEpIl0sWyJkZSIsIkdlcm1hbsSDIl0sWyJmciIsIkZyYW5jZXrEgyJdLFsiZXMiLCJTcGFuaW9s
xIMiXSxbIml0IiwiSXRhbGlhbsSDIl0sWyJwdCIsIlBvcnR1Z2hlesSDIl0sWyJwbCIsIlBvbG9u
ZXrEgyJdLFsiY3MiLCJDZWjEgyJdLFsic2siLCJTbG92YWPEgyJdLFsiaHUiLCJNYWdoaWFyxIMi
XSxbInJvIiwiUm9tw6JuxIMiXSxbInJ1IiwiUnVzxIMiXSxbInVrIiwiVWNyYWluZWFuxIMiXSxb
ImJnIiwiQnVsZ2FyxIMiXSxbImhyIiwiQ3JvYXTEgyJdLFsic3IiLCJTw6JyYsSDIl0sWyJzbCIs
IlNsb3ZlbsSDIl0sWyJlbCIsIkdyZWFjxIMiXSxbInRyIiwiVHVyY8SDIl0sWyJzdiIsIlN1ZWRl
esSDIl0sWyJkYSIsIkRhbmV6xIMiXSxbIm5iIiwiTm9ydmVnaWFuxIMiXSxbImZpIiwiRmlubGFu
ZGV6xIMiXSxbImx0IiwiTGl0dWFuaWFuxIMiXSxbImx2IiwiTGV0b27EgyJdLFsiZXQiLCJFc3Rv
bsSDIl1dLCBsZXZlbHM6IFtbIm9wZXJhdGlvbmFsIiwiT3BlcmHIm2lvbmFsIl0sWyJiYWNoZWxv
ciIsIkJhY2hlbG9yIl0sWyJtYXN0ZXIiLCJNYXN0ZXIiXV0gfSwKKyAgbmw6IHsgaGVhZGluZzog
IkthbmRpZGFhdCIsIG5hbWU6ICJOYWFtIGthbmRpZGFhdCIsIGVtYWlsOiAiRS1tYWlsIGthbmRp
ZGFhdCIsIHRhYWxMYWJlbDogIlRhYWwga2FuZGlkYWF0IiwgbGV2ZWw6ICJOaXZlYXUiLCBwaWNr
OiAiS2llc+KApiIsIGxhbmdzOiBbWyJubCIsIk5lZGVybGFuZHMiXSxbIm5sLUJFIiwiTmVkZXJs
YW5kcyAoQmVsZ2nDqykiXSxbImVuIiwiRW5nZWxzIChWSykiXSxbImVuLVVTIiwiRW5nZWxzIChW
UykiXSxbImRlIiwiRHVpdHMiXSxbImZyIiwiRnJhbnMiXSxbImVzIiwiU3BhYW5zIl0sWyJpdCIs
Ikl0YWxpYWFucyJdLFsicHQiLCJQb3J0dWdlZXMiXSxbInBsIiwiUG9vbHMiXSxbImNzIiwiVHNq
ZWNoaXNjaCJdLFsic2siLCJTbG93YWFrcyJdLFsiaHUiLCJIb25nYWFycyJdLFsicm8iLCJSb2Vt
ZWVucyJdLFsicnUiLCJSdXNzaXNjaCJdLFsidWsiLCJPZWtyYcOvZW5zIl0sWyJiZyIsIkJ1bGdh
YXJzIl0sWyJociIsIktyb2F0aXNjaCJdLFsic3IiLCJTZXJ2aXNjaCJdLFsic2wiLCJTbG92ZWVu
cyJdLFsiZWwiLCJHcmlla3MiXSxbInRyIiwiVHVya3MiXSxbInN2IiwiWndlZWRzIl0sWyJkYSIs
IkRlZW5zIl0sWyJuYiIsIk5vb3JzIl0sWyJmaSIsIkZpbnMiXSxbImx0IiwiTGl0b3V3cyJdLFsi
bHYiLCJMZXRzIl0sWyJldCIsIkVzdHMiXV0sIGxldmVsczogW1sib3BlcmF0aW9uYWwiLCJPcGVy
YXRpb25hbCJdLFsiYmFjaGVsb3IiLCJCYWNoZWxvciJdLFsibWFzdGVyIiwiTWFzdGVyIl1dIH0s
CisgIGVuOiB7IGhlYWRpbmc6ICJDYW5kaWRhdGUiLCBuYW1lOiAiQ2FuZGlkYXRlIG5hbWUiLCBl
bWFpbDogIkNhbmRpZGF0ZSBlbWFpbCIsIHRhYWxMYWJlbDogIkNhbmRpZGF0ZSBsYW5ndWFnZSIs
IGxldmVsOiAiTGV2ZWwiLCBwaWNrOiAiQ2hvb3Nl4oCmIiwgbGFuZ3M6IFtbIm5sIiwiRHV0Y2gi
XSxbIm5sLUJFIiwiRHV0Y2ggKEJlbGdpdW0pIl0sWyJlbiIsIkVuZ2xpc2ggKFVLKSJdLFsiZW4t
VVMiLCJFbmdsaXNoIChVUykiXSxbImRlIiwiR2VybWFuIl0sWyJmciIsIkZyZW5jaCJdLFsiZXMi
LCJTcGFuaXNoIl0sWyJpdCIsIkl0YWxpYW4iXSxbInB0IiwiUG9ydHVndWVzZSJdLFsicGwiLCJQ
b2xpc2giXSxbImNzIiwiQ3plY2giXSxbInNrIiwiU2xvdmFrIl0sWyJodSIsIkh1bmdhcmlhbiJd
LFsicm8iLCJSb21hbmlhbiJdLFsicnUiLCJSdXNzaWFuIl0sWyJ1ayIsIlVrcmFpbmlhbiJdLFsi
YmciLCJCdWxnYXJpYW4iXSxbImhyIiwiQ3JvYXRpYW4iXSxbInNyIiwiU2VyYmlhbiJdLFsic2wi
LCJTbG92ZW5pYW4iXSxbImVsIiwiR3JlZWsiXSxbInRyIiwiVHVya2lzaCJdLFsic3YiLCJTd2Vk
aXNoIl0sWyJkYSIsIkRhbmlzaCJdLFsibmIiLCJOb3J3ZWdpYW4iXSxbImZpIiwiRmlubmlzaCJd
LFsibHQiLCJMaXRodWFuaWFuIl0sWyJsdiIsIkxhdHZpYW4iXSxbImV0IiwiRXN0b25pYW4iXV0s
IGxldmVsczogW1sib3BlcmF0aW9uYWwiLCJPcGVyYXRpb25hbCJdLFsiYmFjaGVsb3IiLCJCYWNo
ZWxvciJdLFsibWFzdGVyIiwiTWFzdGVyIl1dIH0sCisgIGRlOiB7IGhlYWRpbmc6ICJLYW5kaWRh
dCIsIG5hbWU6ICJOYW1lIGRlcyBLYW5kaWRhdGVuIiwgZW1haWw6ICJFLU1haWwgZGVzIEthbmRp
ZGF0ZW4iLCB0YWFsTGFiZWw6ICJTcHJhY2hlIiwgbGV2ZWw6ICJOaXZlYXUiLCBwaWNrOiAiV8Ok
aGxlbuKApiIsIGxhbmdzOiBbWyJubCIsIk5pZWRlcmzDpG5kaXNjaCJdLFsibmwtQkUiLCJOaWVk
ZXJsw6RuZGlzY2ggKEJlbGdpZW4pIl0sWyJlbiIsIkVuZ2xpc2NoIChVSykiXSxbImVuLVVTIiwi
RW5nbGlzY2ggKFVTQSkiXSxbImRlIiwiRGV1dHNjaCJdLFsiZnIiLCJGcmFuesO2c2lzY2giXSxb
ImVzIiwiU3BhbmlzY2giXSxbIml0IiwiSXRhbGllbmlzY2giXSxbInB0IiwiUG9ydHVnaWVzaXNj
aCJdLFsicGwiLCJQb2xuaXNjaCJdLFsiY3MiLCJUc2NoZWNoaXNjaCJdLFsic2siLCJTbG93YWtp
c2NoIl0sWyJodSIsIlVuZ2FyaXNjaCJdLFsicm8iLCJSdW3DpG5pc2NoIl0sWyJydSIsIlJ1c3Np
c2NoIl0sWyJ1ayIsIlVrcmFpbmlzY2giXSxbImJnIiwiQnVsZ2FyaXNjaCJdLFsiaHIiLCJLcm9h
dGlzY2giXSxbInNyIiwiU2VyYmlzY2giXSxbInNsIiwiU2xvd2VuaXNjaCJdLFsiZWwiLCJHcmll
Y2hpc2NoIl0sWyJ0ciIsIlTDvHJraXNjaCJdLFsic3YiLCJTY2h3ZWRpc2NoIl0sWyJkYSIsIkTD
pG5pc2NoIl0sWyJuYiIsIk5vcndlZ2lzY2giXSxbImZpIiwiRmlubmlzY2giXSxbImx0IiwiTGl0
YXVpc2NoIl0sWyJsdiIsIkxldHRpc2NoIl0sWyJldCIsIkVzdG5pc2NoIl1dLCBsZXZlbHM6IFtb
Im9wZXJhdGlvbmFsIiwiT3BlcmF0aW9uYWwiXSxbImJhY2hlbG9yIiwiQmFjaGVsb3IiXSxbIm1h
c3RlciIsIk1hc3RlciJdXSB9LAorICBmcjogeyBoZWFkaW5nOiAiQ2FuZGlkYXQiLCBuYW1lOiAi
Tm9tIGR1IGNhbmRpZGF0IiwgZW1haWw6ICJFLW1haWwgZHUgY2FuZGlkYXQiLCB0YWFsTGFiZWw6
ICJMYW5ndWUiLCBsZXZlbDogIk5pdmVhdSIsIHBpY2s6ICJDaG9pc2ly4oCmIiwgbGFuZ3M6IFtb
Im5sIiwiTsOpZXJsYW5kYWlzIl0sWyJubC1CRSIsIk7DqWVybGFuZGFpcyAoQmVsZ2lxdWUpIl0s
WyJlbiIsIkFuZ2xhaXMgKFJVKSJdLFsiZW4tVVMiLCJBbmdsYWlzIChVUykiXSxbImRlIiwiQWxs
ZW1hbmQiXSxbImZyIiwiRnJhbsOnYWlzIl0sWyJlcyIsIkVzcGFnbm9sIl0sWyJpdCIsIkl0YWxp
ZW4iXSxbInB0IiwiUG9ydHVnYWlzIl0sWyJwbCIsIlBvbG9uYWlzIl0sWyJjcyIsIlRjaMOocXVl
Il0sWyJzayIsIlNsb3ZhcXVlIl0sWyJodSIsIkhvbmdyb2lzIl0sWyJybyIsIlJvdW1haW4iXSxb
InJ1IiwiUnVzc2UiXSxbInVrIiwiVWtyYWluaWVuIl0sWyJiZyIsIkJ1bGdhcmUiXSxbImhyIiwi
Q3JvYXRlIl0sWyJzciIsIlNlcmJlIl0sWyJzbCIsIlNsb3bDqG5lIl0sWyJlbCIsIkdyZWMiXSxb
InRyIiwiVHVyYyJdLFsic3YiLCJTdcOpZG9pcyJdLFsiZGEiLCJEYW5vaXMiXSxbIm5iIiwiTm9y
dsOpZ2llbiJdLFsiZmkiLCJGaW5ub2lzIl0sWyJsdCIsIkxpdHVhbmllbiJdLFsibHYiLCJMZXR0
b24iXSxbImV0IiwiRXN0b25pZW4iXV0sIGxldmVsczogW1sib3BlcmF0aW9uYWwiLCJPcMOpcmF0
aW9ubmVsIl0sWyJiYWNoZWxvciIsIkJhY2hlbG9yIl0sWyJtYXN0ZXIiLCJNYXN0ZXIiXV0gfSwK
KyAgZXM6IHsgaGVhZGluZzogIkNhbmRpZGF0byIsIG5hbWU6ICJOb21icmUgZGVsIGNhbmRpZGF0
byIsIGVtYWlsOiAiQ29ycmVvIGRlbCBjYW5kaWRhdG8iLCB0YWFsTGFiZWw6ICJJZGlvbWEiLCBs
ZXZlbDogIk5pdmVsIiwgcGljazogIkVsZWdpcuKApiIsIGxhbmdzOiBbWyJubCIsIk5lZXJsYW5k
w6lzIl0sWyJubC1CRSIsIk5lZXJsYW5kw6lzIChCw6lsZ2ljYSkiXSxbImVuIiwiSW5nbMOpcyAo
UlUpIl0sWyJlbi1VUyIsIkluZ2zDqXMgKEVFLiBVVS4pIl0sWyJkZSIsIkFsZW3DoW4iXSxbImZy
IiwiRnJhbmPDqXMiXSxbImVzIiwiRXNwYcOxb2wiXSxbIml0IiwiSXRhbGlhbm8iXSxbInB0Iiwi
UG9ydHVndcOpcyJdLFsicGwiLCJQb2xhY28iXSxbImNzIiwiQ2hlY28iXSxbInNrIiwiRXNsb3Zh
Y28iXSxbImh1IiwiSMO6bmdhcm8iXSxbInJvIiwiUnVtYW5vIl0sWyJydSIsIlJ1c28iXSxbInVr
IiwiVWNyYW5pYW5vIl0sWyJiZyIsIkLDumxnYXJvIl0sWyJociIsIkNyb2F0YSJdLFsic3IiLCJT
ZXJiaW8iXSxbInNsIiwiRXNsb3Zlbm8iXSxbImVsIiwiR3JpZWdvIl0sWyJ0ciIsIlR1cmNvIl0s
WyJzdiIsIlN1ZWNvIl0sWyJkYSIsIkRhbsOpcyJdLFsibmIiLCJOb3J1ZWdvIl0sWyJmaSIsIkZp
bsOpcyJdLFsibHQiLCJMaXR1YW5vIl0sWyJsdiIsIkxldMOzbiJdLFsiZXQiLCJFc3RvbmlvIl1d
LCBsZXZlbHM6IFtbIm9wZXJhdGlvbmFsIiwiT3BlcmFjaW9uYWwiXSxbImJhY2hlbG9yIiwiQmFj
aGVsb3IiXSxbIm1hc3RlciIsIk3DoXN0ZXIiXV0gfSwKKyAgcm86IHsgaGVhZGluZzogIkNhbmRp
ZGF0IiwgbmFtZTogIk51bWVsZSBjYW5kaWRhdHVsdWkiLCBlbWFpbDogIkUtbWFpbHVsIGNhbmRp
ZGF0dWx1aSIsIHRhYWxMYWJlbDogIkxpbWLEgyIsIGxldmVsOiAiTml2ZWwiLCBwaWNrOiAiQWxl
Z2XigKYiLCBsYW5nczogW1sibmwiLCJOZWVybGFuZGV6xIMiXSxbIm5sLUJFIiwiTmVlcmxhbmRl
esSDIChCZWxnaWEpIl0sWyJlbiIsIkVuZ2xlesSDIChVSykiXSxbImVuLVVTIiwiRW5nbGV6xIMg
KFNVQSkiXSxbImRlIiwiR2VybWFuxIMiXSxbImZyIiwiRnJhbmNlesSDIl0sWyJlcyIsIlNwYW5p
b2zEgyJdLFsiaXQiLCJJdGFsaWFuxIMiXSxbInB0IiwiUG9ydHVnaGV6xIMiXSxbInBsIiwiUG9s
b25lesSDIl0sWyJjcyIsIkNlaMSDIl0sWyJzayIsIlNsb3ZhY8SDIl0sWyJodSIsIk1hZ2hpYXLE
gyJdLFsicm8iLCJSb23Dom7EgyJdLFsicnUiLCJSdXPEgyJdLFsidWsiLCJVY3JhaW5lYW7EgyJd
LFsiYmciLCJCdWxnYXLEgyJdLFsiaHIiLCJDcm9hdMSDIl0sWyJzciIsIlPDonJixIMiXSxbInNs
IiwiU2xvdmVuxIMiXSxbImVsIiwiR3JlYWPEgyJdLFsidHIiLCJUdXJjxIMiXSxbInN2IiwiU3Vl
ZGV6xIMiXSxbImRhIiwiRGFuZXrEgyJdLFsibmIiLCJOb3J2ZWdpYW7EgyJdLFsiZmkiLCJGaW5s
YW5kZXrEgyJdLFsibHQiLCJMaXR1YW5pYW7EgyJdLFsibHYiLCJMZXRvbsSDIl0sWyJldCIsIkVz
dG9uxIMiXV0sIGxldmVsczogW1sib3BlcmF0aW9uYWwiLCJPcGVyYcibaW9uYWwiXSxbImJhY2hl
bG9yIiwiQmFjaGVsb3IiXSxbIm1hc3RlciIsIk1hc3RlciJdXSB9LApkaWZmIC0tZ2l0IGEvc3Jj
L2RhdGEvdHJhbnNsYXRpb25zLWNvbnRlbnQvZGEuanNvbiBiL3NyYy9kYXRhL3RyYW5zbGF0aW9u
cy1jb250ZW50L2RhLmpzb24KaW5kZXggNTYyOTdiNC4uNWNjOTcwOCAxMDA2NDQKLS0tIGEvc3Jj
L2RhdGEvdHJhbnNsYXRpb25zLWNvbnRlbnQvZGEuanNvbgorKysgYi9zcmMvZGF0YS90cmFuc2xh
dGlvbnMtY29udGVudC9kYS5qc29uCkBAIC00NjEzICs0NjEzIEBACi0gIkJlc3RlLCI6ICJLw6Zy
ZSwiLAorICJCZXN0ZSwiOiAiSGVqLCIsCkBAIC00NjQyICs0NjQyIEBACi0gIkJ1bGdhYXJzIjog
ImJ1bGdhcnNrIiwKKyAiQnVsZ2FhcnMiOiAiQnVsZ2Fyc2siLApAQCAtNDY2NCArNDY2NCBAQAot
ICJMZXRzIjogIkxhZCBvcyIsCisgIkxldHMiOiAiTGV0dGlzayIsCkBAIC00NjY2ICs0NjY2IEBA
Ci0gIkVzdHMiOiAiRXN0cyIsCisgIkVzdHMiOiAiRXN0aXNrIiwKQEAgLTQ2NzIgKzQ2NzIgQEAK
LSAiTG9zc2UgYWZuYW1lLCB6b25kZXIgYWJvbm5lbWVudCI6ICJFbmdhbmdzIGvDuGIsIHVkZW4g
YWJvbm5lbWVudCIsCisgIkxvc3NlIGFmbmFtZSwgem9uZGVyIGFib25uZW1lbnQiOiAiRW5nYW5n
c2vDuGIsIHVkZW4gYWJvbm5lbWVudCIsCkBAIC00NjgxICs0NjgxLDIgQEAKLSAiT256ZSBhc3Nl
c3NtZW50cyB6aWpuIGJlc2NoaWtiYWFyIGluIDI5IHRhYWx2ZXJzaWVzLCB2YW4gTmVkZXJsYW5k
cywgRW5nZWxzLCBEdWl0cywgRnJhbnMgZW4gU3BhYW5zIHRvdCBQb29scywgVHNqZWNoaXNjaCwg
WndlZWRzLCBEZWVucywgVHVya3MsIEdyaWVrcywgT2VrcmFpZW5zIGVuIGRlIEJhbHRpc2NoZSB0
YWxlbi4gRGUga2FuZGlkYWF0IGtpZXN0IHplbGYgZGUgZ2V3ZW5zdGUgdGFhbCBiaWogYWFudmFu
Zywgem9kYXQgdGFhbCBnZWVuIGJlbGVtbWVyaW5nIHZvcm10IHZvb3IgZWVuIGVlcmxpamtlIG1l
dGluZy4iOiAiVm9yZXMgdnVyZGVyaW5nZXIgZmluZGVzIGkgMjkgc3Byb2d2ZXJzaW9uZXIsIGZy
YSBob2xsYW5kc2ssIGVuZ2Vsc2ssIHR5c2ssIGZyYW5zayBvZyBzcGFuc2sgdGlsIHBvbHNrLCB0
amVra2lzaywgc3ZlbnNrLCBkYW5zaywgdHlya2lzaywgZ3LDpnNrLCB1a3JhaW5zayBvZyBkZSBi
YWx0aXNrZSBzcHJvZy4gS2FuZGlkYXRlbiB2w6ZsZ2VyIHNlbHYgZGV0IMO4bnNrZWRlIHNwcm9n
IHZlZCB0ZXN0ZW5zIHN0YXJ0LCBzw6Ugc3Byb2dldCBpa2tlIHVkZ8O4ciBlbiBoaW5kcmluZyBm
b3IgZW4gcmV0ZsOmcmRpZyB2dXJkZXJpbmcuIgorICJPbnplIGFzc2Vzc21lbnRzIHppam4gYmVz
Y2hpa2JhYXIgaW4gMjkgdGFhbHZlcnNpZXMsIHZhbiBOZWRlcmxhbmRzLCBFbmdlbHMsIER1aXRz
LCBGcmFucyBlbiBTcGFhbnMgdG90IFBvb2xzLCBUc2plY2hpc2NoLCBad2VlZHMsIERlZW5zLCBU
dXJrcywgR3JpZWtzLCBPZWtyYWllbnMgZW4gZGUgQmFsdGlzY2hlIHRhbGVuLiBEZSBrYW5kaWRh
YXQga2llc3QgemVsZiBkZSBnZXdlbnN0ZSB0YWFsIGJpaiBhYW52YW5nLCB6b2RhdCB0YWFsIGdl
ZW4gYmVsZW1tZXJpbmcgdm9ybXQgdm9vciBlZW4gZWVybGlqa2UgbWV0aW5nLiI6ICJWb3JlcyB2
dXJkZXJpbmdlciBmaW5kZXMgaSAyOSBzcHJvZ3ZlcnNpb25lciwgZnJhIGhvbGxhbmRzaywgZW5n
ZWxzaywgdHlzaywgZnJhbnNrIG9nIHNwYW5zayB0aWwgcG9sc2ssIHRqZWtraXNrLCBzdmVuc2ss
IGRhbnNrLCB0eXJraXNrLCBncsOmc2ssIHVrcmFpbnNrIG9nIGRlIGJhbHRpc2tlIHNwcm9nLiBL
YW5kaWRhdGVuIHbDpmxnZXIgc2VsdiBkZXQgw7huc2tlZGUgc3Byb2cgdmVkIHRlc3RlbnMgc3Rh
cnQsIHPDpSBzcHJvZ2V0IGlra2UgdWRnw7hyIGVuIGhpbmRyaW5nIGZvciBlbiByZXRmw6ZyZGln
IHZ1cmRlcmluZy4iLAorICJUYWFsIGthbmRpZGFhdCI6ICJLYW5kaWRhdGVucyBzcHJvZyIKZGlm
ZiAtLWdpdCBhL3NyYy9kYXRhL3RyYW5zbGF0aW9ucy1jb250ZW50L3BsLmpzb24gYi9zcmMvZGF0
YS90cmFuc2xhdGlvbnMtY29udGVudC9wbC5qc29uCmluZGV4IDQxMDJiOTAuLjk0ODU1ODggMTAw
NjQ0Ci0tLSBhL3NyYy9kYXRhL3RyYW5zbGF0aW9ucy1jb250ZW50L3BsLmpzb24KKysrIGIvc3Jj
L2RhdGEvdHJhbnNsYXRpb25zLWNvbnRlbnQvcGwuanNvbgpAQCAtNDA0OSArNDA0OSBAQAotICJO
ZWRlcmxhbmRzIjogIkrEmXp5ayBuaWRlcmxhbmR6a2kiLAorICJOZWRlcmxhbmRzIjogIk5pZGVy
bGFuZHpraSIsCkBAIC00MDU1ICs0MDU1IEBACi0gIkZyYW5zIjogIkZyYW5zIiwKKyAiRnJhbnMi
OiAiRnJhbmN1c2tpIiwKQEAgLTQ2MTEsMyArNDYxMSwzIEBACi0gIkplIGFhbnZyYWFnIGJpaiBo
cm1mb3JjZSI6ICJQYcWEc3R3YSB6YXB5dGFuaWUgcHJvc2lteSBraWVyb3dhxIcgbmEgYWRyZXMg
aHJtZm9yY2UiLAotICJCZXN0ZSB7bmFhbX0sIjogIlN6YW5vd255IFBhbmllIHtuYWFtfSwiLAot
ICJCZXN0ZSwiOiAiU3phbm93bmkgUGHFhHN0d28sIiwKKyAiSmUgYWFudnJhYWcgYmlqIGhybWZv
cmNlIjogIlR3b2plIHpnxYJvc3plbmllIHcgaHJtZm9yY2UiLAorICJCZXN0ZSB7bmFhbX0sIjog
IkR6aWXFhCBkb2JyeSB7bmFhbX0sIiwKKyAiQmVzdGUsIjogIkR6aWXFhCBkb2JyeSwiLApAQCAt
NDYyMSArNDYyMSBAQAotICJOZWRlcmxhbmRzIChCZWxnacOrKSI6ICJKxJl6eWsgbmlkZXJsYW5k
emtpIChCZWxnaWEpIiwKKyAiTmVkZXJsYW5kcyAoQmVsZ2nDqykiOiAiTmlkZXJsYW5kemtpIChC
ZWxnaWEpIiwKQEAgLTQ2MjggKzQ2MjggQEAKLSAiUG9ydHVnZWVzIjogIkrEmXp5ayBwb3J0dWdh
bHNraSIsCisgIlBvcnR1Z2VlcyI6ICJQb3J0dWdhbHNraSIsCkBAIC00NjQ0ICs0NjQ0IEBACi0g
Iktyb2F0aXNjaCI6ICJKxJl6eWsgY2hvcndhY2tpIiwKKyAiS3JvYXRpc2NoIjogIkNob3J3YWNr
aSIsCkBAIC00NjY0ICs0NjY0IEBACi0gIkxldHMiOiAiUG96d8OzbG15IiwKKyAiTGV0cyI6ICLF
gW90ZXdza2kiLApAQCAtNDY2NiwyICs0NjY2LDIgQEAKLSAiRXN0cyI6ICJFc3RzIiwKLSAie25h
bWV9IGlzIGVlbiBvbmxpbmUgYXNzZXNzbWVudCB2YW4gaHJtZm9yY2U6IHdldGVuc2NoYXBwZWxp
amsgb25kZXJib3V3ZCwgZGlyZWN0IG9ubGluZSBhZiB0ZSBuZW1lbiBlbiBtZXRlZW4gYnJ1aWti
YWFyLiI6ICJ7bmFtZX0gSmVzdCB0byB0ZXN0IG9ubGluZSBvcHJhY293YW55IHByemV6IGhybWZv
cmNlOiBvcGFydHkgbmEgcG9kc3Rhd2FjaCBuYXVrb3d5Y2gsIGRvc3TEmXBueSBiZXpwb8WbcmVk
bmlvIHcgSW50ZXJuZWNpZSBpIGRhasSFY3kgbmF0eWNobWlhc3Rvd2Ugd3luaWtpLiIsCisgIkVz
dHMiOiAiRXN0b8WEc2tpIiwKKyAie25hbWV9IGlzIGVlbiBvbmxpbmUgYXNzZXNzbWVudCB2YW4g
aHJtZm9yY2U6IHdldGVuc2NoYXBwZWxpamsgb25kZXJib3V3ZCwgZGlyZWN0IG9ubGluZSBhZiB0
ZSBuZW1lbiBlbiBtZXRlZW4gYnJ1aWtiYWFyLiI6ICJ7bmFtZX0gdG8gdGVzdCBvbmxpbmUgb3By
YWNvd2FueSBwcnpleiBocm1mb3JjZTogb3BhcnR5IG5hIHBvZHN0YXdhY2ggbmF1a293eWNoLCBk
b3N0xJlwbnkgYmV6cG/Fm3JlZG5pbyB3IEludGVybmVjaWUgaSBkYWrEhWN5IG5hdHljaG1pYXN0
b3dlIHd5bmlraS4iLApAQCAtNDY3MSArNDY3MSBAQAotICJJbiBtZWVyZGVyZSB0YWxlbiBiZXNj
aGlrYmFhciI6ICJEb3N0xJlwbmEgdyB3aWVsdSBqxJl6eWthY2giLAorICJJbiBtZWVyZGVyZSB0
YWxlbiBiZXNjaGlrYmFhciI6ICJEb3N0xJlwbnkgdyB3aWVsdSBqxJl6eWthY2giLApAQCAtNDY3
NCwzICs0Njc0LDMgQEAKLSAiSmUgb2VmZW52cmFnZW4gdm9vciB7dGl0ZWx9IjogIlB5dGFuaWEg
xId3aWN6ZW5pb3dlIGRvdHljesSFY2Ugc3Ryb255IHt0aXRlbH0iLAotICJIYWxsbyB7bmFhbX0s
IjogIldpdGFtLCB7bmFhbX0sIiwKLSAiSGFsbG8sIjogIldpdGFtLCIsCisgIkplIG9lZmVudnJh
Z2VuIHZvb3Ige3RpdGVsfSI6ICJQeXRhbmlhIMSHd2ljemVuaW93ZToge3RpdGVsfSIsCisgIkhh
bGxvIHtuYWFtfSwiOiAiRHppZcWEIGRvYnJ5IHtuYWFtfSwiLAorICJIYWxsbywiOiAiRHppZcWE
IGRvYnJ5LCIsCkBAIC00NjgxICs0NjgxLDIgQEAKLSAiT256ZSBhc3Nlc3NtZW50cyB6aWpuIGJl
c2NoaWtiYWFyIGluIDI5IHRhYWx2ZXJzaWVzLCB2YW4gTmVkZXJsYW5kcywgRW5nZWxzLCBEdWl0
cywgRnJhbnMgZW4gU3BhYW5zIHRvdCBQb29scywgVHNqZWNoaXNjaCwgWndlZWRzLCBEZWVucywg
VHVya3MsIEdyaWVrcywgT2VrcmFpZW5zIGVuIGRlIEJhbHRpc2NoZSB0YWxlbi4gRGUga2FuZGlk
YWF0IGtpZXN0IHplbGYgZGUgZ2V3ZW5zdGUgdGFhbCBiaWogYWFudmFuZywgem9kYXQgdGFhbCBn
ZWVuIGJlbGVtbWVyaW5nIHZvcm10IHZvb3IgZWVuIGVlcmxpamtlIG1ldGluZy4iOiAiTmFzemUg
dGVzdHkgc8SFIGRvc3TEmXBuZSB3IDI5IHdlcnNqYWNoIGrEmXp5a293eWNoLCBvZCBob2xlbmRl
cnNraWVnbywgYW5naWVsc2tpZWdvLCBuaWVtaWVja2llZ28sIGZyYW5jdXNraWVnbyBpIGhpc3pw
YcWEc2tpZWdvIHBvIHBvbHNraSwgY3plc2tpLCBzendlZHpraSwgZHXFhHNraSwgdHVyZWNraSwg
Z3JlY2tpLCB1a3JhacWEc2tpIG9yYXogasSZenlraSBiYcWCdHlja2llLiBLYW5keWRhdCBzYW0g
d3liaWVyYSBwcmVmZXJvd2FueSBqxJl6eWsgbmEgcG9jesSFdGt1IHRlc3R1LCBkemnEmWtpIGN6
ZW11IGrEmXp5ayBuaWUgc3Rhbm93aSBwcnplc3prb2R5IHcgcHJ6ZXByb3dhZHplbml1IHJ6ZXRl
bG5laiBvY2VueS4iCisgIk9uemUgYXNzZXNzbWVudHMgemlqbiBiZXNjaGlrYmFhciBpbiAyOSB0
YWFsdmVyc2llcywgdmFuIE5lZGVybGFuZHMsIEVuZ2VscywgRHVpdHMsIEZyYW5zIGVuIFNwYWFu
cyB0b3QgUG9vbHMsIFRzamVjaGlzY2gsIFp3ZWVkcywgRGVlbnMsIFR1cmtzLCBHcmlla3MsIE9l
a3JhaWVucyBlbiBkZSBCYWx0aXNjaGUgdGFsZW4uIERlIGthbmRpZGFhdCBraWVzdCB6ZWxmIGRl
IGdld2Vuc3RlIHRhYWwgYmlqIGFhbnZhbmcsIHpvZGF0IHRhYWwgZ2VlbiBiZWxlbW1lcmluZyB2
b3JtdCB2b29yIGVlbiBlZXJsaWprZSBtZXRpbmcuIjogIk5hc3plIHRlc3R5IHPEhSBkb3N0xJlw
bmUgdyAyOSB3ZXJzamFjaCBqxJl6eWtvd3ljaCwgb2QgaG9sZW5kZXJza2llZ28sIGFuZ2llbHNr
aWVnbywgbmllbWllY2tpZWdvLCBmcmFuY3Vza2llZ28gaSBoaXN6cGHFhHNraWVnbyBwbyBwb2xz
a2ksIGN6ZXNraSwgc3p3ZWR6a2ksIGR1xYRza2ksIHR1cmVja2ksIGdyZWNraSwgdWtyYWnFhHNr
aSBvcmF6IGrEmXp5a2kgYmHFgnR5Y2tpZS4gS2FuZHlkYXQgc2FtIHd5YmllcmEgcHJlZmVyb3dh
bnkgasSZenlrIG5hIHBvY3rEhXRrdSB0ZXN0dSwgZHppxJlraSBjemVtdSBqxJl6eWsgbmllIHN0
YW5vd2kgcHJ6ZXN6a29keSB3IHByemVwcm93YWR6ZW5pdSByemV0ZWxuZWogb2NlbnkuIiwKKyAi
VGFhbCBrYW5kaWRhYXQiOiAiSsSZenlrIGthbmR5ZGF0YSIKZGlmZiAtLWdpdCBhL3NyYy9kYXRh
L3RyYW5zbGF0aW9ucy1jb250ZW50L3N2Lmpzb24gYi9zcmMvZGF0YS90cmFuc2xhdGlvbnMtY29u
dGVudC9zdi5qc29uCmluZGV4IDZhNDEyZTUuLmUwZDVhNzIgMTAwNjQ0Ci0tLSBhL3NyYy9kYXRh
L3RyYW5zbGF0aW9ucy1jb250ZW50L3N2Lmpzb24KKysrIGIvc3JjL2RhdGEvdHJhbnNsYXRpb25z
LWNvbnRlbnQvc3YuanNvbgpAQCAtNDYxMiwyICs0NjEyLDIgQEAKLSAiQmVzdGUge25hYW19LCI6
ICJLw6RyYSB7bmFhbX0sIiwKLSAiQmVzdGUsIjogIkLDpHN0ZSwiLAorICJCZXN0ZSB7bmFhbX0s
IjogIkhlaiB7bmFhbX0sIiwKKyAiQmVzdGUsIjogIkhlaiwiLApAQCAtNDY0OCArNDY0OCBAQAot
ICJTbG92ZWVucyI6ICJzbG92ZW5za2EiLAorICJTbG92ZWVucyI6ICJTbG92ZW5za2EiLApAQCAt
NDY1OCArNDY1OCBAQAotICJOb29ycyI6ICJub3Jza2EiLAorICJOb29ycyI6ICJOb3Jza2EiLApA
QCAtNDY2NCArNDY2NCBAQAotICJMZXRzIjogIkzDpXQgb3NzIiwKKyAiTGV0cyI6ICJMZXR0aXNr
YSIsCkBAIC00NjY2ICs0NjY2IEBACi0gIkVzdHMiOiAiRXN0cyIsCisgIkVzdHMiOiAiRXN0bmlz
a2EiLApAQCAtNDY4MCwyICs0NjgwLDMgQEAKLSAiSGV0IGRvY3VtZW50IGJldmF0IHZvb3JiZWVs
ZHZyYWdlbi4gWmUga29tZW4gbmlldCB1aXQgZGUgZWNodGUgdnJhZ2VubGlqc3QgZW4gamUgYW50
d29vcmRlbiB3b3JkZW4gbmlldCBiZXdhYXJkLiI6ICJEb2t1bWVudGV0IGlubmVow6VsbGVyIGV4
ZW1wZWxmcsOlZ29yLiBEZSBrb21tZXIgaW50ZSBmcsOlbiBkZW4gcmlrdGlnYSBmcsOlZ2Vmb3Jt
dWzDpHJldCBvY2ggZGluYSBzdmFyIHNwYXJhcyBpbnRlLiIsCi0gIk9uemUgYXNzZXNzbWVudHMg
emlqbiBiZXNjaGlrYmFhciBpbiAyOSB0YWFsdmVyc2llcywgdmFuIE5lZGVybGFuZHMsIEVuZ2Vs
cywgRHVpdHMsIEZyYW5zIGVuIFNwYWFucyB0b3QgUG9vbHMsIFRzamVjaGlzY2gsIFp3ZWVkcywg
RGVlbnMsIFR1cmtzLCBHcmlla3MsIE9la3JhaWVucyBlbiBkZSBCYWx0aXNjaGUgdGFsZW4uIERl
IGthbmRpZGFhdCBraWVzdCB6ZWxmIGRlIGdld2Vuc3RlIHRhYWwgYmlqIGFhbnZhbmcsIHpvZGF0
IHRhYWwgZ2VlbiBiZWxlbW1lcmluZyB2b3JtdCB2b29yIGVlbiBlZXJsaWprZSBtZXRpbmcuIjog
IlbDpXJhIHRlc3RlciBmaW5ucyB0aWxsZ8OkbmdsaWdhIHDDpSAyOSBzcHLDpWssIGZyw6VuIG5l
ZGVybMOkbmRza2EsIGVuZ2Vsc2thLCB0eXNrYSwgZnJhbnNrYSBvY2ggc3BhbnNrYSB0aWxsIHBv
bHNrYSwgdGplY2tpc2thLCBzdmVuc2thLCBkYW5za2EsIHR1cmtpc2thLCBncmVraXNrYSwgdWty
YWluc2thIG9jaCBkZSBiYWx0aXNrYSBzcHLDpWtlbi4gS2FuZGlkYXRlbiB2w6RsamVyIHNqw6Rs
diDDtm5za2F0IHNwcsOlayB2aWQgdGVzdGV0cyBiw7ZyamFuLCBzw6UgYXR0IHNwcsOla2V0IGlu
dGUgdXRnw7ZyIGV0dCBoaW5kZXIgZsO2ciBlbiByw6R0dHZpcyB1dHbDpHJkZXJpbmcuIgorICJI
ZXQgZG9jdW1lbnQgYmV2YXQgdm9vcmJlZWxkdnJhZ2VuLiBaZSBrb21lbiBuaWV0IHVpdCBkZSBl
Y2h0ZSB2cmFnZW5saWpzdCBlbiBqZSBhbnR3b29yZGVuIHdvcmRlbiBuaWV0IGJld2FhcmQuIjog
IkRva3VtZW50ZXQgaW5uZWjDpWxsZXIgZXhlbXBlbGZyw6Vnb3IuIERlIGtvbW1lciBpbnRlIGZy
w6VuIGRldCByaWt0aWdhIGZyw6VnZWZvcm11bMOkcmV0IG9jaCBkaW5hIHN2YXIgc3BhcmFzIGlu
dGUuIiwKKyAiT256ZSBhc3Nlc3NtZW50cyB6aWpuIGJlc2NoaWtiYWFyIGluIDI5IHRhYWx2ZXJz
aWVzLCB2YW4gTmVkZXJsYW5kcywgRW5nZWxzLCBEdWl0cywgRnJhbnMgZW4gU3BhYW5zIHRvdCBQ
b29scywgVHNqZWNoaXNjaCwgWndlZWRzLCBEZWVucywgVHVya3MsIEdyaWVrcywgT2VrcmFpZW5z
IGVuIGRlIEJhbHRpc2NoZSB0YWxlbi4gRGUga2FuZGlkYWF0IGtpZXN0IHplbGYgZGUgZ2V3ZW5z
dGUgdGFhbCBiaWogYWFudmFuZywgem9kYXQgdGFhbCBnZWVuIGJlbGVtbWVyaW5nIHZvcm10IHZv
b3IgZWVuIGVlcmxpamtlIG1ldGluZy4iOiAiVsOlcmEgdGVzdGVyIGZpbm5zIHRpbGxnw6RuZ2xp
Z2EgaSAyOSBzcHLDpWt2ZXJzaW9uZXIsIGZyw6VuIG5lZGVybMOkbmRza2EsIGVuZ2Vsc2thLCB0
eXNrYSwgZnJhbnNrYSBvY2ggc3BhbnNrYSB0aWxsIHBvbHNrYSwgdGplY2tpc2thLCBzdmVuc2th
LCBkYW5za2EsIHR1cmtpc2thLCBncmVraXNrYSwgdWtyYWluc2thIG9jaCBkZSBiYWx0aXNrYSBz
cHLDpWtlbi4gS2FuZGlkYXRlbiB2w6RsamVyIHNqw6RsdiDDtm5za2F0IHNwcsOlayB2aWQgdGVz
dGV0cyBiw7ZyamFuLCBzw6UgYXR0IHNwcsOla2V0IGludGUgdXRnw7ZyIGV0dCBoaW5kZXIgZsO2
ciBlbiByw6R0dHZpcyB1dHbDpHJkZXJpbmcuIiwKKyAiVGFhbCBrYW5kaWRhYXQiOiAiS2FuZGlk
YXRlbnMgc3Byw6VrIgo=
B64EOF
base64 -d /tmp/86.b64 > /tmp/86.patch
if grep -q "taalLabel" src/data/component-teksten.js; then
  echo "De patch stond er al in, alleen het vastleggen nog."
else
  git apply --unidiff-zero /tmp/86.patch
fi
rm -f /tmp/86.b64 /tmp/86.patch

git add -A
git commit -q -F - <<'MSGEOF'
Taalnamen, aanhef en onderwerp in de nieuwe talen rechtgezet

Controle op patch 85, vijf vondsten.

1. DeepL las Lets, de taal, als het Engelse lets en maakte er een werkwoord
   van: Pozwolmy, Lad os, Lat oss. Ests bleef onvertaald. Alle 29 taalnamen
   staan nu met de hand goed in het Pools, Deens en Zweeds, inclusief de
   hoofdletters die DeepL wisselend zette.
2. Het label Taal kandidaat bleef in elke taal Nederlands. De sleutel heette
   lang en die staat in GEEN_TEKST van de vertaallaag, waar hij als taalcode
   geldt en niet als tekst. De sleutel heet nu taalLabel.
3. De Poolse aanhef in de antwoordmail werd Szanowny Panie, dus mannelijk.
   Nu Dzien dobry. Het Zweedse Kara is te familiair voor een zakelijke mail en
   werd Hej, en het Deense Kaere zonder naam werd Hej.
4. Het Poolse onderwerp van de antwoordmail werd een opdracht in plaats van
   een onderwerp en is nu Twoje zgloszenie w hrmforce. Verder drie losse
   correcties: een Zweeds geslachtsfout, een Deens woord dat aan elkaar hoort
   en een Poolse zin die met Jest to begon.
5. De productomschrijving in de shop stond in negen talen in de bron van elke
   shoppagina. Nu alleen de eigen taal, dus geen Nederlands meer onder een
   Poolse url en ruim 4 kB minder per pagina.

Geen enkel adres verandert, er komen geen kapotte links bij en de Nederlandse
pagina's blijven gelijk op de shoppagina na, die alleen lichter wordt.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>
MSGEOF

git push
echo
echo "Klaar. Patch 86 staat op main."
